// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

namespace api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("api.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("api.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("IBAN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Interests")
                        .HasColumnType("TEXT");

                    b.Property<string>("Introduction")
                        .HasColumnType("TEXT");

                    b.Property<string>("KnownAs")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("LookingFor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("hospital_id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ltk")
                        .HasColumnType("INTEGER");

                    b.Property<string>("worked_in")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("api.Entities.AppUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("api.Entities.ClassTableVlad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("caption")
                        .HasColumnType("TEXT");

                    b.Property<int>("current_user_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("dataXas")
                        .HasColumnType("TEXT");

                    b.Property<string>("dataYas")
                        .HasColumnType("TEXT");

                    b.Property<int>("hospitalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vlads");
                });

            modelBuilder.Entity("api.Entities.Class_Aortic_Surgery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("aneurysm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("aneurysm_type")
                        .HasColumnType("TEXT");

                    b.Property<bool>("coarctation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("dissection")
                        .HasColumnType("INTEGER");

                    b.Property<string>("dissection_onset")
                        .HasColumnType("TEXT");

                    b.Property<string>("dissection_type")
                        .HasColumnType("TEXT");

                    b.Property<string>("indication")
                        .HasColumnType("TEXT");

                    b.Property<string>("operative_technique")
                        .HasColumnType("TEXT");

                    b.Property<bool>("other_congenital")
                        .HasColumnType("INTEGER");

                    b.Property<string>("pathology")
                        .HasColumnType("TEXT");

                    b.Property<int>("procedure_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("range")
                        .HasColumnType("TEXT");

                    b.Property<string>("stent_graft_technique")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AorticSurgeries");
                });

            modelBuilder.Entity("api.Entities.Class_CABG", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ANGLE01")
                        .HasColumnType("TEXT");

                    b.Property<string>("ANGLE02")
                        .HasColumnType("TEXT");

                    b.Property<string>("ANGLE03")
                        .HasColumnType("TEXT");

                    b.Property<string>("ANGLE04")
                        .HasColumnType("TEXT");

                    b.Property<string>("ANGLE05")
                        .HasColumnType("TEXT");

                    b.Property<string>("ANGLE06")
                        .HasColumnType("TEXT");

                    b.Property<string>("B1_CONDUIT")
                        .HasColumnType("TEXT");

                    b.Property<string>("B1_DONOR")
                        .HasColumnType("TEXT");

                    b.Property<string>("B1_LOCPROC")
                        .HasColumnType("TEXT");

                    b.Property<string>("B1_SITE")
                        .HasColumnType("TEXT");

                    b.Property<string>("B1_SITEPA")
                        .HasColumnType("TEXT");

                    b.Property<string>("B1_TYPE_DA")
                        .HasColumnType("TEXT");

                    b.Property<string>("B2_CONDUIT")
                        .HasColumnType("TEXT");

                    b.Property<string>("B2_DONOR")
                        .HasColumnType("TEXT");

                    b.Property<string>("B2_LOCPROC")
                        .HasColumnType("TEXT");

                    b.Property<string>("B2_SITE")
                        .HasColumnType("TEXT");

                    b.Property<string>("B2_SITEPA")
                        .HasColumnType("TEXT");

                    b.Property<string>("B2_TYPE_DA")
                        .HasColumnType("TEXT");

                    b.Property<string>("B3_CONDUIT")
                        .HasColumnType("TEXT");

                    b.Property<string>("B3_DONOR")
                        .HasColumnType("TEXT");

                    b.Property<string>("B3_LOCPROC")
                        .HasColumnType("TEXT");

                    b.Property<string>("B3_SITE")
                        .HasColumnType("TEXT");

                    b.Property<string>("B3_SITEPA")
                        .HasColumnType("TEXT");

                    b.Property<string>("B3_TYPE_DA")
                        .HasColumnType("TEXT");

                    b.Property<string>("B4_CONDUIT")
                        .HasColumnType("TEXT");

                    b.Property<string>("B4_DONOR")
                        .HasColumnType("TEXT");

                    b.Property<string>("B4_LOCPROC")
                        .HasColumnType("TEXT");

                    b.Property<string>("B4_SITE")
                        .HasColumnType("TEXT");

                    b.Property<string>("B4_SITEPA")
                        .HasColumnType("TEXT");

                    b.Property<string>("B4_TYPE_DA")
                        .HasColumnType("TEXT");

                    b.Property<string>("B5_CONDUIT")
                        .HasColumnType("TEXT");

                    b.Property<string>("B5_DONOR")
                        .HasColumnType("TEXT");

                    b.Property<string>("B5_LOCPROC")
                        .HasColumnType("TEXT");

                    b.Property<string>("B5_SITE")
                        .HasColumnType("TEXT");

                    b.Property<string>("B5_SITEPA")
                        .HasColumnType("TEXT");

                    b.Property<string>("B5_TYPE_DA")
                        .HasColumnType("TEXT");

                    b.Property<string>("B6_CONDUIT")
                        .HasColumnType("TEXT");

                    b.Property<string>("B6_DONOR")
                        .HasColumnType("TEXT");

                    b.Property<string>("B6_LOCPROC")
                        .HasColumnType("TEXT");

                    b.Property<string>("B6_SITE")
                        .HasColumnType("TEXT");

                    b.Property<string>("B6_SITEPA")
                        .HasColumnType("TEXT");

                    b.Property<string>("B6_TYPE_DA")
                        .HasColumnType("TEXT");

                    b.Property<string>("CAB")
                        .HasColumnType("TEXT");

                    b.Property<string>("DIAM01")
                        .HasColumnType("TEXT");

                    b.Property<string>("DIAM02")
                        .HasColumnType("TEXT");

                    b.Property<string>("DIAM03")
                        .HasColumnType("TEXT");

                    b.Property<string>("DIAM04")
                        .HasColumnType("TEXT");

                    b.Property<string>("DIAM05")
                        .HasColumnType("TEXT");

                    b.Property<string>("DIAM06")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PATIENT_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PROCEDURE_ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q01")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q02")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q03")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q04")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q05")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q06")
                        .HasColumnType("TEXT");

                    b.Property<string>("UNPLANNED_CAB")
                        .HasColumnType("TEXT");

                    b.Property<string>("art01")
                        .HasColumnType("TEXT");

                    b.Property<string>("art02")
                        .HasColumnType("TEXT");

                    b.Property<string>("art03")
                        .HasColumnType("TEXT");

                    b.Property<string>("art04")
                        .HasColumnType("TEXT");

                    b.Property<string>("art05")
                        .HasColumnType("TEXT");

                    b.Property<string>("art06")
                        .HasColumnType("TEXT");

                    b.Property<string>("course")
                        .HasColumnType("TEXT");

                    b.Property<string>("leg_harvest_location")
                        .HasColumnType("TEXT");

                    b.Property<string>("leg_harvest_technique")
                        .HasColumnType("TEXT");

                    b.Property<string>("radial_harvest_location")
                        .HasColumnType("TEXT");

                    b.Property<string>("radial_harvest_technique")
                        .HasColumnType("TEXT");

                    b.Property<int?>("tachtig_switch")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CABGS");
                });

            modelBuilder.Entity("api.Entities.Class_CPB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Antiarrhythmics")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BVAD")
                        .HasColumnType("TEXT");

                    b.Property<string>("CARDIOPLEGIA")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CARDIOPLEGIA_TEMP_COLD")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CARDIOPLEGIA_TEMP_WARM")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CARDIOPLEGIA_TYPE")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CARDIOVERSION")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CROSS_CLAMP_TIME")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IABP")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IABP_DATE")
                        .HasColumnType("TEXT");

                    b.Property<string>("IABP_IND")
                        .HasColumnType("TEXT");

                    b.Property<string>("IABP_OPTIONS")
                        .HasColumnType("TEXT");

                    b.Property<int?>("INFUSION_DOSE_CONT")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("INFUSION_DOSE_INT")
                        .HasColumnType("INTEGER");

                    b.Property<string>("INFUSION_MODE_ANTE")
                        .HasColumnType("TEXT");

                    b.Property<int?>("INFUSION_MODE_RETRO")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("INOTROPES")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LOWEST_CORE_TEMP")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LVAD")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PACING_ATRIAL")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PACING_HARV")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PACING_VENTRICULAR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PERFUSION_TIME")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PROCEDURE_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RVAD")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SKIN_INCISION_START_TIME")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SKIN_INCISION_STOP_TIME")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TAH")
                        .HasColumnType("TEXT");

                    b.Property<string>("VAD")
                        .HasColumnType("TEXT");

                    b.Property<string>("a1")
                        .HasColumnType("TEXT");

                    b.Property<string>("a2")
                        .HasColumnType("TEXT");

                    b.Property<string>("a3")
                        .HasColumnType("TEXT");

                    b.Property<string>("a4")
                        .HasColumnType("TEXT");

                    b.Property<string>("acp_circ")
                        .HasColumnType("TEXT");

                    b.Property<string>("aoOCCL")
                        .HasColumnType("TEXT");

                    b.Property<string>("cardiac_support")
                        .HasColumnType("TEXT");

                    b.Property<string>("cardiopl_temp")
                        .HasColumnType("TEXT");

                    b.Property<string>("cardiopl_timing")
                        .HasColumnType("TEXT");

                    b.Property<int?>("clamp_start_hr")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("clamp_start_min")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("clamp_stop_hr")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("clamp_stop_min")
                        .HasColumnType("INTEGER");

                    b.Property<string>("cns_protect")
                        .HasColumnType("TEXT");

                    b.Property<int?>("cns_time_1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("cns_time_2")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("cns_time_3")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("cpb_start_hr")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("cpb_start_min")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("cpb_stop_hr")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("cpb_stop_min")
                        .HasColumnType("INTEGER");

                    b.Property<string>("cpb_used")
                        .HasColumnType("TEXT");

                    b.Property<string>("deep_hypo")
                        .HasColumnType("TEXT");

                    b.Property<string>("deep_hypo_rcp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("long_isch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("myoplasty")
                        .HasColumnType("TEXT");

                    b.Property<string>("nonCMProtect")
                        .HasColumnType("TEXT");

                    b.Property<short?>("nonCMProtect_type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("opcab_attempt")
                        .HasColumnType("TEXT");

                    b.Property<string>("other_cardiac_support")
                        .HasColumnType("TEXT");

                    b.Property<string>("other_cns_protect")
                        .HasColumnType("TEXT");

                    b.Property<string>("v1")
                        .HasColumnType("TEXT");

                    b.Property<string>("v2")
                        .HasColumnType("TEXT");

                    b.Property<string>("v3")
                        .HasColumnType("TEXT");

                    b.Property<string>("v4")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CPBS");
                });

            modelBuilder.Entity("api.Entities.Class_Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("active")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("courseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<string>("diploma")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("location")
                        .HasColumnType("TEXT");

                    b.Property<float>("price")
                        .HasColumnType("REAL");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<int?>("userId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("api.Entities.Class_Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("image")
                        .HasColumnType("TEXT");

                    b.Property<string>("liscense_to_kill")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<string>("profession")
                        .HasColumnType("TEXT");

                    b.Property<string>("selected_hospital_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("user_name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("api.Entities.Class_Epa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("date_finished")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("date_started")
                        .HasColumnType("TEXT");

                    b.Property<bool>("finished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("grade")
                        .HasColumnType("TEXT");

                    b.Property<string>("image")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("option_1")
                        .HasColumnType("TEXT");

                    b.Property<string>("option_2")
                        .HasColumnType("TEXT");

                    b.Property<string>("option_3")
                        .HasColumnType("TEXT");

                    b.Property<string>("option_4")
                        .HasColumnType("TEXT");

                    b.Property<string>("option_5")
                        .HasColumnType("TEXT");

                    b.Property<string>("option_6")
                        .HasColumnType("TEXT");

                    b.Property<string>("option_7")
                        .HasColumnType("TEXT");

                    b.Property<int?>("userId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("Epaas");
                });

            modelBuilder.Entity("api.Entities.Class_Final_operative_report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Anaesthesist")
                        .HasColumnType("TEXT");

                    b.Property<string>("AorticLineA")
                        .HasColumnType("TEXT");

                    b.Property<string>("AorticLineB")
                        .HasColumnType("TEXT");

                    b.Property<string>("AorticLineC")
                        .HasColumnType("TEXT");

                    b.Property<string>("Assistant")
                        .HasColumnType("TEXT");

                    b.Property<string>("Attending")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("TEXT");

                    b.Property<string>("FreeText")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderText1")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderText2")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderText3")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderText4")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderText5")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderText6")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderText7")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderText8")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderText9")
                        .HasColumnType("TEXT");

                    b.Property<string>("HospitalUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("MedRecNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("MitralLineA")
                        .HasColumnType("TEXT");

                    b.Property<string>("MitralLineB")
                        .HasColumnType("TEXT");

                    b.Property<string>("MitralLineC")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatieDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Perfusionist")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcedureDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel10")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel11")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel12")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel13")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel14")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel15")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel16")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel17")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel18")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel19")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel20")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel21")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel22")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel23")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel24")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel25")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel26")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel27")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel28")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel29")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel30")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel31")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel32")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel33")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel34")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel35")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel36")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel37")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel38")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel39")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel4")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel40")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel41")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel42")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel43")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel44")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel45")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel46")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel47")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel48")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel49")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel5")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel50")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel51")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel52")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel53")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel54")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel55")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel56")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel57")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel58")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel59")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel6")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel60")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel61")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel62")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel63")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel7")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel8")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regel9")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surgeon")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<int>("procedure_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("finalReports");
                });

            modelBuilder.Entity("api.Entities.Class_Hospital", b =>
                {
                    b.Property<int>("hospitalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fax")
                        .HasColumnType("TEXT");

                    b.Property<string>("HospitalName")
                        .HasColumnType("TEXT");

                    b.Property<string>("HospitalNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpReportDetails1")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpReportDetails2")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpReportDetails3")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpReportDetails4")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpReportDetails5")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpReportDetails6")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpReportDetails7")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpReportDetails8")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpReportDetails9")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegExpr")
                        .HasColumnType("TEXT");

                    b.Property<string>("SampleMrn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Selected_Hospital_Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.Property<bool>("usesOnlineValveInventory")
                        .HasColumnType("INTEGER");

                    b.HasKey("hospitalId");

                    b.ToTable("Hospitals");
                });

            modelBuilder.Entity("api.Entities.Class_LTX", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AcceptorProcedureStart")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DonorProcedureStart")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DonorStartIschemia")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DonorStartReperfusion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Indication")
                        .HasColumnType("TEXT");

                    b.Property<int>("PROCEDURE_ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeOfTX")
                        .HasColumnType("TEXT");

                    b.Property<string>("startHr01")
                        .HasColumnType("TEXT");

                    b.Property<string>("startHr02")
                        .HasColumnType("TEXT");

                    b.Property<string>("startHr03")
                        .HasColumnType("TEXT");

                    b.Property<string>("startHr04")
                        .HasColumnType("TEXT");

                    b.Property<string>("startMin01")
                        .HasColumnType("TEXT");

                    b.Property<string>("startMin02")
                        .HasColumnType("TEXT");

                    b.Property<string>("startMin03")
                        .HasColumnType("TEXT");

                    b.Property<string>("startMin04")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LTXs");
                });

            modelBuilder.Entity("api.Entities.Class_Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CCS")
                        .HasColumnType("TEXT");

                    b.Property<int>("EuroScoreNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IsPreviousIntervention")
                        .HasColumnType("TEXT");

                    b.Property<string>("LVEF")
                        .HasColumnType("TEXT");

                    b.Property<string>("MRN")
                        .HasColumnType("TEXT");

                    b.Property<string>("NOPM")
                        .HasColumnType("TEXT");

                    b.Property<string>("NYHA")
                        .HasColumnType("TEXT");

                    b.Property<string>("active_endocarditis")
                        .HasColumnType("TEXT");

                    b.Property<string>("copd")
                        .HasColumnType("TEXT");

                    b.Property<int>("creat_number")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("crit_arrythmia")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("crit_iabp")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("crit_inotropes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("crit_pacemaker")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("crit_renal_failure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("crit_resuscitation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("crit_shock")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("crit_ventilated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("critical_preoperative_state")
                        .HasColumnType("INTEGER");

                    b.Property<int>("dead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("diabetes_on_insulin")
                        .HasColumnType("TEXT");

                    b.Property<bool>("dialysis")
                        .HasColumnType("INTEGER");

                    b.Property<string>("extra_cardiac_arteriopathy")
                        .HasColumnType("TEXT");

                    b.Property<string>("gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("height")
                        .HasColumnType("TEXT");

                    b.Property<string>("log_score")
                        .HasColumnType("TEXT");

                    b.Property<string>("poor_mobility")
                        .HasColumnType("TEXT");

                    b.Property<string>("previous_cardiac_surgery")
                        .HasColumnType("TEXT");

                    b.Property<string>("reason_emergent")
                        .HasColumnType("TEXT");

                    b.Property<string>("reason_urgent")
                        .HasColumnType("TEXT");

                    b.Property<string>("recent_mi")
                        .HasColumnType("TEXT");

                    b.Property<int>("soort_procedure")
                        .HasColumnType("INTEGER");

                    b.Property<string>("surgery_on_thoracic_aorta")
                        .HasColumnType("TEXT");

                    b.Property<string>("systolic_pa_pressure")
                        .HasColumnType("TEXT");

                    b.Property<string>("timing")
                        .HasColumnType("TEXT");

                    b.Property<string>("weight")
                        .HasColumnType("TEXT");

                    b.Property<string>("weight_of_intervention")
                        .HasColumnType("TEXT");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("api.Entities.Class_PostOp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autologous_Blood")
                        .HasColumnType("TEXT");

                    b.Property<string>("Blood_Products")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DISCHARGE_DATE")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EXTUBATION_1_DATE")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EXTUBATION_DATE")
                        .HasColumnType("TEXT");

                    b.Property<int>("FFP")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ICU_ARRIVAL_1_DATE")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ICU_ARRIVAL_DATE")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ICU_DISCHARGE_1_DATE")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ICU_DISCHARGE_DATE")
                        .HasColumnType("TEXT");

                    b.Property<string>("ICU_Stay_1")
                        .HasColumnType("TEXT");

                    b.Property<string>("ICU_Stay_2")
                        .HasColumnType("TEXT");

                    b.Property<string>("ICU_Stay_3")
                        .HasColumnType("TEXT");

                    b.Property<int>("PATIENT_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PROCEDURE_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Platelets")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("REINTUBATION_DATE")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vent_Stay_1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vent_Stay_2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vent_Stay_3")
                        .HasColumnType("TEXT");

                    b.Property<string>("When_Used")
                        .HasColumnType("TEXT");

                    b.Property<string>("activities_discharge")
                        .HasColumnType("TEXT");

                    b.Property<string>("complicatie_1")
                        .HasColumnType("TEXT");

                    b.Property<string>("complicatie_2")
                        .HasColumnType("TEXT");

                    b.Property<string>("complicatie_3")
                        .HasColumnType("TEXT");

                    b.Property<string>("complicatie_4")
                        .HasColumnType("TEXT");

                    b.Property<string>("complicatie_5")
                        .HasColumnType("TEXT");

                    b.Property<string>("complicatie_6")
                        .HasColumnType("TEXT");

                    b.Property<string>("complicatie_7")
                        .HasColumnType("TEXT");

                    b.Property<string>("complicatie_8")
                        .HasColumnType("TEXT");

                    b.Property<string>("complicatie_9")
                        .HasColumnType("TEXT");

                    b.Property<short>("dead_cause")
                        .HasColumnType("INTEGER");

                    b.Property<short>("dead_location")
                        .HasColumnType("INTEGER");

                    b.Property<short>("discharge_diagnosis")
                        .HasColumnType("INTEGER");

                    b.Property<string>("full_description")
                        .HasColumnType("TEXT");

                    b.Property<string>("highest_creatinine")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("mortality_date")
                        .HasColumnType("TEXT");

                    b.Property<short>("overleden_na_deze_operatie")
                        .HasColumnType("INTEGER");

                    b.Property<string>("readmitted")
                        .HasColumnType("TEXT");

                    b.Property<string>("reintubated")
                        .HasColumnType("TEXT");

                    b.Property<string>("sent_to")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PostOps");
                });

            modelBuilder.Entity("api.Entities.Class_Preview_Operative_report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("procedure_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("regel_1")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_10")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_11")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_12")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_13")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_14")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_15")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_16")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_17")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_18")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_19")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_2")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_20")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_21")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_22")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_23")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_24")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_25")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_26")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_27")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_28")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_29")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_3")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_30")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_31")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_32")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_33")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_4")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_5")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_6")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_7")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_8")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_9")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Previews");
                });

            modelBuilder.Entity("api.Entities.Class_Procedure", b =>
                {
                    b.Property<int>("ProcedureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Class_PatientPatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment3")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfSurgery")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedAnaesthesist")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedAssistant")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedEmergencyTiming")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedInotropes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedNurse1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedNurse2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedPacemaker")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedPerfusionist")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedPericard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedPleura")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedResponsibleSurgeon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedStartHr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedStartMin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedStopHr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedStopMin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedSurgeon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedTiming")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedUrgentTiming")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sequence")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SurgeryBeforeNextWorkingDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("emailHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("fdType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("hospital")
                        .HasColumnType("INTEGER");

                    b.Property<int>("refPhys")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProcedureId");

                    b.HasIndex("Class_PatientPatientId");

                    b.ToTable("Procedures");
                });

            modelBuilder.Entity("api.Entities.Class_Ref_Phys", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .HasColumnType("TEXT");

                    b.Property<string>("city")
                        .HasColumnType("TEXT");

                    b.Property<string>("country")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("fax")
                        .HasColumnType("TEXT");

                    b.Property<int>("hospital_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("image")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("postcode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("send_email")
                        .HasColumnType("INTEGER");

                    b.Property<string>("state")
                        .HasColumnType("TEXT");

                    b.Property<string>("street")
                        .HasColumnType("TEXT");

                    b.Property<string>("tel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RefPhys");
                });

            modelBuilder.Entity("api.Entities.Class_Suggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("regel_10_a")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_10_b")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_10_c")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_11_a")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_11_b")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_11_c")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_12_a")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_12_b")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_12_c")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_13_a")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_13_b")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_13_c")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_14_a")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_14_b")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_14_c")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_15")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_16")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_17")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_18")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_19")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_1_a")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_1_b")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_1_c")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_20")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_21")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_22")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_23")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_24")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_25")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_26")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_27")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_28")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_29")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_2_a")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_2_b")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_2_c")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_30")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_31")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_32")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_33")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_3_a")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_3_b")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_3_c")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_4_a")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_4_b")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_4_c")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_5_a")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_5_b")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_5_c")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_6_a")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_6_b")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_6_c")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_7_a")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_7_b")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_7_c")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_8_a")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_8_b")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_8_c")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_9_a")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_9_b")
                        .HasColumnType("TEXT");

                    b.Property<string>("regel_9_c")
                        .HasColumnType("TEXT");

                    b.Property<int>("soort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("user")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("api.Entities.Class_Valve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Combined")
                        .HasColumnType("TEXT");

                    b.Property<string>("EXPLANT")
                        .HasColumnType("TEXT");

                    b.Property<string>("IMPLANT")
                        .HasColumnType("TEXT");

                    b.Property<string>("Implant_Position")
                        .HasColumnType("TEXT");

                    b.Property<string>("MODEL")
                        .HasColumnType("TEXT");

                    b.Property<string>("MODEL_EXP")
                        .HasColumnType("TEXT");

                    b.Property<string>("Memo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcedureAetiology")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcedureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcedureType")
                        .HasColumnType("TEXT");

                    b.Property<string>("REPAIR_TYPE")
                        .HasColumnType("TEXT");

                    b.Property<string>("RING_USED")
                        .HasColumnType("TEXT");

                    b.Property<string>("SERIAL_EXP")
                        .HasColumnType("TEXT");

                    b.Property<string>("SERIAL_IMP")
                        .HasColumnType("TEXT");

                    b.Property<string>("SIZE")
                        .HasColumnType("TEXT");

                    b.Property<string>("SIZE_EXP")
                        .HasColumnType("TEXT");

                    b.Property<string>("TYPE")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TYPE_EXP")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProcedureId");

                    b.ToTable("Valves");
                });

            modelBuilder.Entity("api.Entities.Class_Valve_Code", b =>
                {
                    b.Property<int>("codeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("code")
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<int>("hospitalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("position")
                        .HasColumnType("TEXT");

                    b.Property<int>("soort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("type")
                        .HasColumnType("TEXT");

                    b.Property<int>("valveTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("codeId");

                    b.HasIndex("hospitalId");

                    b.ToTable("Class_Valve_Code");
                });

            modelBuilder.Entity("api.Entities.Class_minInv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ACUTE_FLOW")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ACUTE_FLOW_DETAILS")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AL_TIME")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CONVERSION_DETAILS")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CONVERSION_TO_STANDARD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CX_TIME")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IABP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IABP_WHEN")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IABP_WHY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LAD_TIME")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LIMA_HARVEST")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NUMBER_OF_INCISIONS")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PRIMARY_INCISION")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PRIMARY_INCISION_DETAILS")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PROCEDURE_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RCA_TIME")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ROBOT")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ROBOT_AORTIC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ROBOT_CABG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ROBOT_MITRAL")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ROBOT_PULMONARY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ROBOT_TRICUSPID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SHUNT")
                        .HasColumnType("INTEGER");

                    b.Property<int>("STRATEGY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SUTURE")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VESSEL")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MinInvs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("api.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("api.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("api.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("api.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Entities.AppUserRole", b =>
                {
                    b.HasOne("api.Entities.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Entities.Class_Course", b =>
                {
                    b.HasOne("api.Entities.AppUser", "user")
                        .WithMany("Courses")
                        .HasForeignKey("userId");

                    b.Navigation("user");
                });

            modelBuilder.Entity("api.Entities.Class_Epa", b =>
                {
                    b.HasOne("api.Entities.AppUser", "user")
                        .WithMany("Epa")
                        .HasForeignKey("userId");

                    b.Navigation("user");
                });

            modelBuilder.Entity("api.Entities.Class_Procedure", b =>
                {
                    b.HasOne("api.Entities.Class_Patient", "Class_Patient")
                        .WithMany("procedures")
                        .HasForeignKey("Class_PatientPatientId");

                    b.Navigation("Class_Patient");
                });

            modelBuilder.Entity("api.Entities.Class_Valve", b =>
                {
                    b.HasOne("api.Entities.Class_Procedure", "procedure")
                        .WithMany("ValvesUsed")
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("procedure");
                });

            modelBuilder.Entity("api.Entities.Class_Valve_Code", b =>
                {
                    b.HasOne("api.Entities.Class_Hospital", "hospital")
                        .WithMany("valvecodes")
                        .HasForeignKey("hospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hospital");
                });

            modelBuilder.Entity("api.Entities.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("api.Entities.AppUser", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Epa");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("api.Entities.Class_Hospital", b =>
                {
                    b.Navigation("valvecodes");
                });

            modelBuilder.Entity("api.Entities.Class_Patient", b =>
                {
                    b.Navigation("procedures");
                });

            modelBuilder.Entity("api.Entities.Class_Procedure", b =>
                {
                    b.Navigation("ValvesUsed");
                });
#pragma warning restore 612, 618
        }
    }
}
