using System;

namespace api.DTOs
{
    public class CardioDetailsDTO
    {
        public int id { get; set; }
        public string center_id { get; set; }
        public int registry_id { get; set; }
        public byte[] hemodynamics { get; set; }
        public string cassette_id { get; set; }
        public string contributor_id { get; set; }
        public int patient_age { get; set; }
        public int patient_gender { get; set; }
        public int indication { get; set; }
        public int support_mode { get; set; }
        public int time_supported { get; set; }
        public string comment1 { get; set; }
        public string comment2 { get; set; }
        public string comment3 { get; set; }
        public string comment4 { get; set; }
        public string comment5 { get; set; }
        public bool page_1_complete { get; set; }
        public bool page_2_complete { get; set; }
        public bool page_3_complete { get; set; }
        public bool page_4_complete { get; set; }
        public bool page_5_complete { get; set; }
        public string support_mode_other { get; set; }
        public int selected_cannulation_site_1 { get; set; }
        public int selected_cannulation_site_2 { get; set; }
        public int selected_cannulation_site_3 { get; set; }
        public int selected_size_1 { get; set; }
        public int selected_size_2 { get; set; }
        public int selected_size_3 { get; set; }
        public int selected_length_1 { get; set; }
        public int selected_length_2 { get; set; }
        public int selected_length_3 { get; set; }
        public int selected_vv_size { get; set; }
        public bool percutaneous_1 { get; set; }
        public bool percutaneous_2 { get; set; }
        public bool percutaneous_3 { get; set; }
        public bool double_lumen { get; set; }
        public int selected_age { get; set; }
        public Nullable<double> selected_weight { get; set; }
        public Nullable<double> selected_height { get; set; }
        public int selected_fac { get; set; }
        public int selected_intubated { get; set; }
        public int selected_arrest { get; set; }
        public int selected_btt { get; set; }
        public bool ox_failure { get; set; }
        public bool tub_rupture { get; set; }
        public bool pump_malf { get; set; }
        public bool heat_malf { get; set; }
        public bool clots { get; set; }
        public bool air_circuit { get; set; }
        public bool conn_crack { get; set; }
        public bool cannula_problems { get; set; }
        public bool hemo { get; set; }
        public bool hemo_gi { get; set; }
        public bool hemo_ca { get; set; }
        public bool hemo_su { get; set; }
        public bool hemo_he { get; set; }
        public bool hemo_di { get; set; }
        public bool neuro { get; set; }
        public bool neuro_br { get; set; }
        public bool neuro_se { get; set; }
        public bool neuro_ee { get; set; }
        public bool neuro_in { get; set; }
        public bool neuro_he { get; set; }
        public bool renal { get; set; }
        public bool renal_cr_1 { get; set; }
        public bool renal_cr_2 { get; set; }
        public bool renal_di { get; set; }
        public bool renal_he { get; set; }
        public bool renal_ca { get; set; }
        public bool pulm { get; set; }
        public bool pulm_pn { get; set; }
        public bool pulm_pu { get; set; }
        public bool cp { get; set; }
        public bool cp_in { get; set; }
        public bool cp_my { get; set; }
        public bool cp_hy { get; set; }
        public bool cp_pda_1 { get; set; }
        public bool cp_ta_1 { get; set; }
        public bool cp_pda_2 { get; set; }
        public bool cp_ta_2 { get; set; }
        public bool cp_cp { get; set; }
        public bool cp_ca { get; set; }
        public bool cp_pda_3 { get; set; }
        public bool cp_pda_4 { get; set; }
        public bool cp_ta_3 { get; set; }
        public bool infect { get; set; }
        public bool infect_cu { get; set; }
        public bool infect_wb { get; set; }
        public bool meta { get; set; }
        public bool meta_gl_1 { get; set; }
        public bool meta_gl_2 { get; set; }
        public bool meta_ph_1 { get; set; }
        public bool meta_ph_2 { get; set; }
        public bool meta_hy { get; set; }
        public int selected_reason_death { get; set; }
        public int selected_reason { get; set; }
        public string reason_cns { get; set; }
        public string reason_pulmonary { get; set; }
        public string reason_cardiac { get; set; }
        public string reason_liver { get; set; }
        public string reason_infection { get; set; }
        public string reason_other { get; set; }
        public int selected_repair { get; set; }
        public bool discharged_alive { get; set; }
        public int selected_discharge_location { get; set; }
        public DateTime discharge { get; set; }
        public DateTime extubation { get; set; }
        public DateTime death_date { get; set; }
        public int discharge_hours { get; set; }
        public int extubation_hours { get; set; }
        public int death_date_hours { get; set; }
        public int discharge_minutes { get; set; }
        public int extubation_minutes { get; set; }
        public int death_date_minutes { get; set; }
        public DateTime start { get; set; }
        public int start_hour { get; set; }
        public int start_min { get; set; }
        public DateTime stop { get; set; }
        public int stop_hour { get; set; }
        public int stop_min { get; set; }
        public DateTime date_death_followup { get; set; }
        public int one_year_followup { get; set; }
        public DateTime last_followup { get; set; }
        public int lldp { get; set; }
        public int lldp_diam { get; set; }
        public int lldp_length { get; set; }
    }
}